language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
addons:
  apt:
    packages:
      - kpartx
      - qemu-system-arm
      - zerofree
install:
#Download raspbian image
  - wget 'https://downloads.raspberrypi.org/raspbian_lite_latest' -O raspbian.img.zip
  - unzip raspbian.img.zip
  - mv *raspbian*.img raspbian.img
#image update
  - export MOUNT_POINT="${HOME}/root_mount"
#region qemu
  - wget 'https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu-4.4.13-jessie' -O kernel-qemu
  - export QEMU_OPTS=(-kernel kernel-qemu -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append 'root=/dev/sda2 rootfstype=ext4 rw' -hda raspbian.img -net user,hostfwd=tcp::10022-:22,hostfwd=tcp::18069-:8069 -net nic -nographic)
script:
#Region enlarge image
  - dd if=/dev/zero bs=1M count=2048 >> raspbian.img
  - ./fdisk.sh raspbian.img
  - export LOOP_MAPPER_PATH=/dev/mapper/${LOOP_MAPPER_PATH}$(kpartx -avs posbox.img | tail -n 1 | cut -d ' ' -f 3)
  - echo LOOP_MAPPER_PATH="${LOOP_MAPPER_PATH}"
  - echo MOUNT_POINT="${MOUNT_POINT}"
  - echo QEMU_OPTS="${QEMU_OPTS}"
  - sleep 5
  - e2fsck -f "${LOOP_MAPPER_PATH}"
  - resize2fs "${LOOP_MAPPER_PATH}"
  - mkdir "${MOUNT_POINT}"
  - mount "${LOOP_MAPPER_PATH}" "${MOUNT_POINT}"
  - sleep 2
  - cp -a pi-stage0 "${MOUNT_POINT}"
  - umount "${MOUNT_POINT}"
  - qemu-system-arm "${QEMU_OPTS[@]}"