sudo: required
dist: trusty
services:
  - docker
env:
  global:
    - QEMU_KERNEL_URL="https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu-4.4.13-jessie"
    - QEMU_KERNEL=${TRAVIS_BUILD_DIR}/kernel-qemu
    - QEMU=qemu-system-arm
    - QEMU_CPU=arm1176
    - QEMU_MACHINE=versatilepb
    - QEMU_OPTS="-nographic -monitor none"
    - IMAGE_SOURCE="http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-09-08/2017-09-07-raspbian-stretch-lite.zip"
    - IMAGE_TMP=/tmp/raspbian.zip
    - IMAGE_PRISTINE=${TRAVIS_BUILD_DIR}/raspbian-stretch-lite-pristine.img
    - IMAGE_DEST=${TRAVIS_BUILD_DIR}/raspbian-target.img
    - DOCKER_TAG="travis-dev"
cache:
  directories:
    - ${QEMU_KERNEL}
    - ${IMAGE_PRISTINE}
before_install:
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-key update && sudo apt-get update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine
  - docker --version
  - docker build . --tag=${DOCKER_TAG}
script:
  - ./prepare.sh
  - docker run --rm -it --privileged \
    --volume ${TRAVIS_BUILD_DIR}:/data \
    -w /data \
    -e "IMAGE_PRISTINE=${IMAGE_PRISTINE}" \
    -e "IMAGE_DEST=${IMAGE_DEST}" \
    ${DOCKER_TAG} \
    "build.sh"
