sudo: required
services:
  - docker
script:
  - docker build . --tag="maitredede/qemupi"
  - docker run --rm -it --privileged --mount type=bind,source="$(pwd)",target=/data -w /data "maitredede/qemupi" "build.sh"
