language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
addons:
  apt:
    packages:
      - kpartx
      - qemu-system-arm
      - zerofree
      - rsync
  artifacts:
    debug: true
    paths:
      - raspbian.img
cache:
  directories:
    - qemu
install:
  # xenial does not seams to have addons/apt
  # - sudo apt-get install -y kpartx qemu-system-arm zerofree rsync
  - ./build-qemu.sh
  - qemu-system-arm --version
  - ${HOME}/qemu-bin --version
script:
  - sudo ./build.sh
