sudo: required
services:
  - docker
before_install:
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-key update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine
  - docker --version
  - docker --help
  - docker run --help
script:
  - docker build . --tag="maitredede/qemupi"
  - docker run --rm -it --privileged --volume "$(pwd)":/data -w /data "maitredede/qemupi" "build.sh"
