language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
addons:
  apt:
    packages:
      - kpartx
      - qemu-system-arm
      - zerofree
      - rsync
  # artifacts:
  #   debug: true
  #   paths:
  #     - raspbian.img
  #     - build-qemu.log
  #     - build-image.log
script:
  - sudo ./build.sh
