language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
dist: xenial
addons:
  apt:
    packages:
      - kpartx
      - qemu-system-arm
      - zerofree
      - rsync
  # artifacts:
  #   debug: true
  #   paths:
  #     - raspbian.img
  #     - build-qemu.log
  #     - build-image.log
install:
  - sudo apt-get update
  - sudo apt-get install -y kpartx qemu-system-arm zerofree rsync
script:
  - ./build.sh
