language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
addons:
  apt:
    packages:
      - kpartx
      - qemu-system-arm
      - zerofree
      - rsync
  # artifacts:
  #   debug: true
  #   paths:
  #     - raspbian.img
  #     - build-qemu.log
  #     - build-image.log
cache:
  directories:
    - qemu
install:
  # xenial does not seams to have addons/apt
  # - sudo apt-get install -y kpartx qemu-system-arm zerofree rsync
  - ./build-qemu.sh
script:
  - sudo ./build.sh
